spring:
    datasource:
        url: jdbc:mysql://mysql01:3306/tournament
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    mail:
        host: mailcatcher01
        port: 1025
graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL
app:
    host: localhost
    