spring:
    datasource:
        url: jdbc:mysql://rds-ucwork.ckatqfkgvt4x.ap-northeast-1.rds.amazonaws.com:3306/ucwork
        username: rds_ucwork_user
        password: p4|TR~*8
        driver-class-name: com.mysql.jdbc.Driver
    mail:
        host: mailcatcher01
        port: 1025
    velocity:
        enabled: false
        charset: UTF-8
        cache: false
graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL
app:
    schema: https
    host: ucwork.xyz
    port: 443
logging:
    file: logs/application-tennis.log
cloud.aws:
  region:
    static: us-east-1