package club.uctennis.tournament.domain.model;

import java.time.LocalDateTime;

public class FlywaySchemaHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_rank
     *
     * @mbg.generated
     */
    private Integer installedRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.script
     *
     * @mbg.generated
     */
    private String script;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.checksum
     *
     * @mbg.generated
     */
    private Integer checksum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_by
     *
     * @mbg.generated
     */
    private String installedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_on
     *
     * @mbg.generated
     */
    private LocalDateTime installedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.execution_time
     *
     * @mbg.generated
     */
    private Integer executionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.success
     *
     * @mbg.generated
     */
    private Boolean success;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.installed_rank
     *
     * @return the value of flyway_schema_history.installed_rank
     *
     * @mbg.generated
     */
    public Integer getInstalledRank() {
        return installedRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.installed_rank
     *
     * @param installedRank the value for flyway_schema_history.installed_rank
     *
     * @mbg.generated
     */
    public void setInstalledRank(Integer installedRank) {
        this.installedRank = installedRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.version
     *
     * @return the value of flyway_schema_history.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.version
     *
     * @param version the value for flyway_schema_history.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.description
     *
     * @return the value of flyway_schema_history.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.description
     *
     * @param description the value for flyway_schema_history.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.type
     *
     * @return the value of flyway_schema_history.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.type
     *
     * @param type the value for flyway_schema_history.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.script
     *
     * @return the value of flyway_schema_history.script
     *
     * @mbg.generated
     */
    public String getScript() {
        return script;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.script
     *
     * @param script the value for flyway_schema_history.script
     *
     * @mbg.generated
     */
    public void setScript(String script) {
        this.script = script;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.checksum
     *
     * @return the value of flyway_schema_history.checksum
     *
     * @mbg.generated
     */
    public Integer getChecksum() {
        return checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.checksum
     *
     * @param checksum the value for flyway_schema_history.checksum
     *
     * @mbg.generated
     */
    public void setChecksum(Integer checksum) {
        this.checksum = checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.installed_by
     *
     * @return the value of flyway_schema_history.installed_by
     *
     * @mbg.generated
     */
    public String getInstalledBy() {
        return installedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.installed_by
     *
     * @param installedBy the value for flyway_schema_history.installed_by
     *
     * @mbg.generated
     */
    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.installed_on
     *
     * @return the value of flyway_schema_history.installed_on
     *
     * @mbg.generated
     */
    public LocalDateTime getInstalledOn() {
        return installedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.installed_on
     *
     * @param installedOn the value for flyway_schema_history.installed_on
     *
     * @mbg.generated
     */
    public void setInstalledOn(LocalDateTime installedOn) {
        this.installedOn = installedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.execution_time
     *
     * @return the value of flyway_schema_history.execution_time
     *
     * @mbg.generated
     */
    public Integer getExecutionTime() {
        return executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.execution_time
     *
     * @param executionTime the value for flyway_schema_history.execution_time
     *
     * @mbg.generated
     */
    public void setExecutionTime(Integer executionTime) {
        this.executionTime = executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.success
     *
     * @return the value of flyway_schema_history.success
     *
     * @mbg.generated
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.success
     *
     * @param success the value for flyway_schema_history.success
     *
     * @mbg.generated
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }
}