package club.uctennis.tournament.domain.model;

import java.time.LocalDateTime;

public class OnetimeTokens {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetime_tokens.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetime_tokens.pre_entry_id
     *
     * @mbg.generated
     */
    private Integer preEntryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetime_tokens.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetime_tokens.limited_date
     *
     * @mbg.generated
     */
    private LocalDateTime limitedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetime_tokens.create_date
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetime_tokens.update_date
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetime_tokens.id
     *
     * @return the value of onetime_tokens.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetime_tokens.id
     *
     * @param id the value for onetime_tokens.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetime_tokens.pre_entry_id
     *
     * @return the value of onetime_tokens.pre_entry_id
     *
     * @mbg.generated
     */
    public Integer getPreEntryId() {
        return preEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetime_tokens.pre_entry_id
     *
     * @param preEntryId the value for onetime_tokens.pre_entry_id
     *
     * @mbg.generated
     */
    public void setPreEntryId(Integer preEntryId) {
        this.preEntryId = preEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetime_tokens.token
     *
     * @return the value of onetime_tokens.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetime_tokens.token
     *
     * @param token the value for onetime_tokens.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetime_tokens.limited_date
     *
     * @return the value of onetime_tokens.limited_date
     *
     * @mbg.generated
     */
    public LocalDateTime getLimitedDate() {
        return limitedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetime_tokens.limited_date
     *
     * @param limitedDate the value for onetime_tokens.limited_date
     *
     * @mbg.generated
     */
    public void setLimitedDate(LocalDateTime limitedDate) {
        this.limitedDate = limitedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetime_tokens.create_date
     *
     * @return the value of onetime_tokens.create_date
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetime_tokens.create_date
     *
     * @param createDate the value for onetime_tokens.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetime_tokens.update_date
     *
     * @return the value of onetime_tokens.update_date
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetime_tokens.update_date
     *
     * @param updateDate the value for onetime_tokens.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }
}