package club.uctennis.tournament.domain.model;

import java.time.LocalDateTime;

public class Tournaments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tournaments.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tournaments.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tournaments.subtitle
     *
     * @mbg.generated
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tournaments.date
     *
     * @mbg.generated
     */
    private LocalDateTime date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tournaments.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tournaments.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tournaments.id
     *
     * @return the value of tournaments.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tournaments.id
     *
     * @param id the value for tournaments.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tournaments.title
     *
     * @return the value of tournaments.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tournaments.title
     *
     * @param title the value for tournaments.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tournaments.subtitle
     *
     * @return the value of tournaments.subtitle
     *
     * @mbg.generated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tournaments.subtitle
     *
     * @param subtitle the value for tournaments.subtitle
     *
     * @mbg.generated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tournaments.date
     *
     * @return the value of tournaments.date
     *
     * @mbg.generated
     */
    public LocalDateTime getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tournaments.date
     *
     * @param date the value for tournaments.date
     *
     * @mbg.generated
     */
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tournaments.image
     *
     * @return the value of tournaments.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tournaments.image
     *
     * @param image the value for tournaments.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tournaments.description
     *
     * @return the value of tournaments.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tournaments.description
     *
     * @param description the value for tournaments.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}