package club.uctennis.tournament.domain.mapper;

import club.uctennis.tournament.domain.model.FlywaySchemaHistory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FlywaySchemaHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated
     */
    @Delete({
        "delete from flyway_schema_history",
        "where installed_rank = #{installedRank,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated
     */
    @Insert({
        "insert into flyway_schema_history (installed_rank, version, ",
        "description, type, ",
        "script, checksum, ",
        "installed_by, installed_on, ",
        "execution_time, success)",
        "values (#{installedRank,jdbcType=INTEGER}, #{version,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{script,jdbcType=VARCHAR}, #{checksum,jdbcType=INTEGER}, ",
        "#{installedBy,jdbcType=VARCHAR}, #{installedOn,jdbcType=TIMESTAMP}, ",
        "#{executionTime,jdbcType=INTEGER}, #{success,jdbcType=BIT})"
    })
    int insert(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated
     */
    int insertSelective(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "installed_rank, version, description, type, script, checksum, installed_by, ",
        "installed_on, execution_time, success",
        "from flyway_schema_history",
        "where installed_rank = #{installedRank,jdbcType=INTEGER}"
    })
    @ResultMap("club.uctennis.tournament.domain.mapper.FlywaySchemaHistoryMapper.BaseResultMap")
    FlywaySchemaHistory selectByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated
     */
    @Update({
        "update flyway_schema_history",
        "set version = #{version,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "script = #{script,jdbcType=VARCHAR},",
          "checksum = #{checksum,jdbcType=INTEGER},",
          "installed_by = #{installedBy,jdbcType=VARCHAR},",
          "installed_on = #{installedOn,jdbcType=TIMESTAMP},",
          "execution_time = #{executionTime,jdbcType=INTEGER},",
          "success = #{success,jdbcType=BIT}",
        "where installed_rank = #{installedRank,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FlywaySchemaHistory record);
}