package club.uctennis.tournament.domain.mapper;

import club.uctennis.tournament.domain.model.Tournaments;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TournamentsMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tournaments
   * @mbg.generated
   */
  @Delete({"delete from tournaments", "where id = #{id,jdbcType=INTEGER}"})
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tournaments
   * @mbg.generated
   */
  @Insert({"insert into tournaments (id, title, ", "subtitle, date, ", "image, description, ",
      "create_date, update_date)", "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
      "#{subtitle,jdbcType=VARCHAR}, #{date,jdbcType=TIMESTAMP}, ",
      "#{image,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
      "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP})"})
  int insert(Tournaments record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tournaments
   * @mbg.generated
   */
  int insertSelective(Tournaments record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tournaments
   * @mbg.generated
   */
  @Select({"select", "id, title, subtitle, date, image, description, create_date, update_date",
      "from tournaments", "where id = #{id,jdbcType=INTEGER}"})
  @ResultMap("club.uctennis.tournament.domain.mapper.TournamentsMapper.BaseResultMap")
  Tournaments selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tournaments
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(Tournaments record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tournaments
   * @mbg.generated
   */
  @Update({"update tournaments", "set title = #{title,jdbcType=VARCHAR},",
      "subtitle = #{subtitle,jdbcType=VARCHAR},", "date = #{date,jdbcType=TIMESTAMP},",
      "image = #{image,jdbcType=VARCHAR},", "description = #{description,jdbcType=VARCHAR},",
      "create_date = #{createDate,jdbcType=TIMESTAMP},",
      "update_date = #{updateDate,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=INTEGER}"})
  int updateByPrimaryKey(Tournaments record);
}